# Generated by Django 5.1.6 on 2025-06-08 13:06

import companies.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom de la société')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('nombre_employes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_autorisation', models.DateField(blank=True, null=True, verbose_name="Date d'autorisation d'exploitation")),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('condition', models.TextField(blank=True, null=True, verbose_name="Condition d'application")),
            ],
            options={
                'verbose_name': 'Document requis',
                'verbose_name_plural': 'Documents requis',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=companies.models.document_upload_path, verbose_name='Fichier')),
                ('date_submission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='companies.company', verbose_name='Société')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='companies.requireddocument', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document soumis',
                'verbose_name_plural': 'Documents soumis',
                'ordering': ['-date_submission'],
                'unique_together': {('company', 'document')},
            },
        ),
    ]
