# Generated by Django 5.1.6 on 2025-06-14 00:06

import companies.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom de la société')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('nombre_employes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_autorisation', models.DateField(blank=True, null=True, verbose_name="Date d'autorisation d'exploitation")),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('condition', models.TextField(blank=True, null=True, verbose_name="Condition d'application")),
            ],
            options={
                'verbose_name': 'Document requis',
                'verbose_name_plural': 'Documents requis',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=companies.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), companies.models.validate_file_size], verbose_name='Fichier')),
                ('date_submission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='companies.company', verbose_name='Société')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='companies.requireddocument', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document soumis',
                'verbose_name_plural': 'Documents soumis',
                'ordering': ['-date_submission'],
                'unique_together': {('company', 'document')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/versions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), companies.models.validate_file_size], verbose_name='Fichier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes de version')),
                ('is_current', models.BooleanField(default=True, verbose_name='Version actuelle')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='companies.documentsubmission', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='DPMGProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100, verbose_name='Préfecture')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse physique')),
                ('code_dpmg', models.CharField(max_length=20, unique=True, verbose_name='Code DPMG')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dpmg_logos/', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpmg_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil DPMG',
                'verbose_name_plural': 'Profils DPMG',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='dpmg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.dpmgprofile', verbose_name='DPMG'),
        ),
    ]
