# Generated by Django 5.1.6 on 2025-06-08 17:41

import companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=companies.models.document_upload_path, verbose_name='Fichier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_current', models.BooleanField(default=True, help_text='Indique si cette version est la version actuelle du document', verbose_name='Version actuelle')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur cette version', verbose_name='Notes de version')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='companies.documentsubmission', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-date_creation'],
            },
        ),
    ]
