# Generated by Django 5.1.6 on 2025-06-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_documentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={},
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='fichier',
            field=models.FileField(upload_to='documents/versions/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Version actuelle'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de version'),
        ),
        migrations.CreateModel(
            name='DPMGProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100, verbose_name='Préfecture')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse physique')),
                ('code_dpmg', models.CharField(max_length=20, unique=True, verbose_name='Code DPMG')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dpmg_logos/', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpmg_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil DPMG',
                'verbose_name_plural': 'Profils DPMG',
            },
        ),
    ]
