# Generated by Django 5.1.6 on 2025-06-09 15:14

import companies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_documentversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='fichier',
            field=models.FileField(upload_to=companies.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), companies.models.validate_file_size], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='fichier',
            field=models.FileField(upload_to='documents/versions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), companies.models.validate_file_size], verbose_name='Fichier'),
        ),
    ]
