# Generated by Django 5.1.6 on 2025-06-08 13:06

import administration_docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DECRET', 'Décret'), ('ARRETE', 'Arrêté'), ('NOTE', 'Note de service')], max_length=10, verbose_name='Type de document')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date_enregistrement', models.DateField(verbose_name="Date d'enregistrement")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to=administration_docs.models.admin_doc_upload_path, verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Document administratif',
                'verbose_name_plural': 'Documents administratifs',
                'ordering': ['-date_enregistrement', 'type'],
                'unique_together': {('type', 'numero')},
            },
        ),
    ]
